# Generated by Django 5.1.4 on 2026-03-02 18:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


def migrate_files_to_chunks(apps, schema_editor):
    """
    Convert existing File records into the chunk model.
    Each existing file becomes a single-chunk file.
    """
    File = apps.get_model("files", "File")
    FileChunk = apps.get_model("files", "FileChunk")

    for file in File.objects.filter(storage_account__isnull=False).exclude(
        external_file_id=""
    ):
        FileChunk.objects.create(
            file=file,
            chunk_index=0,
            storage_account=file.storage_account,
            external_chunk_id=file.external_file_id,
            chunk_size=file.file_size,
            upload_status="uploaded",
        )
        file.total_chunks = 1
        file.save(update_fields=["total_chunks"])


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_remove_file_encryption_key_remove_file_file_and_more"),
        ("storage", "0001_initial"),
    ]

    operations = [
        # Step 1: Add new fields/model while keeping old columns
        migrations.AddField(
            model_name="file",
            name="total_chunks",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="FileChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("chunk_index", models.PositiveIntegerField()),
                (
                    "external_chunk_id",
                    models.CharField(default="", max_length=255),
                ),
                ("chunk_size", models.BigIntegerField()),
                (
                    "upload_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("uploaded", "Uploaded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="files.file",
                    ),
                ),
                (
                    "storage_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chunks",
                        to="storage.storageaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("file", "chunk_index"),
                        name="unique_file_chunk_index",
                    )
                ],
            },
        ),
        # Step 2: Data migration — move existing files into chunks
        migrations.RunPython(
            migrate_files_to_chunks,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 3: Drop the old columns from File
        migrations.RemoveField(
            model_name="file",
            name="external_file_id",
        ),
        migrations.RemoveField(
            model_name="file",
            name="storage_account",
        ),
    ]
