# Generated by Django 5.1.4 on 2026-03-08 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0001_initial"),
        ("files", "0004_file_chunking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="file",
            name="unique_file_name_owner",
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.UniqueConstraint(
                fields=("name", "drive"),
                name="unique_file_name_drive",
                violation_error_code="unique_file_name_drive",
                violation_error_message="A file with this name already exists in this drive",
            ),
        ),
    ]
