# Generated by Django 5.1.4 on 2026-03-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storageaccount",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google_drive", "GOOGLE_DRIVE"),
                    ("onedrive", "ONEDRIVE"),
                    ("dropbox", "DROPBOX"),
                ],
                max_length=20,
            ),
        ),
    ]
